config/routes.rb
Rails.application.routes.draw do
  resources :users, only:[:index, :new, :create, :destroy]
  
  resources :tweets
  
  resources :likes, only: [:create, :destroy]
  
  get 'tops/main'
  post 'tops/login'
  get 'tops/logout'
  root 'tops#main'
end

app/models/like.rb
class Like < ActiveRecord::Base
  validates :user_id, presence: true
  validates :tweet_id, presence: true
  
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates :message, presence: true, length: {maximum: 140}
  validates :user_id, presence: true
  
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :like_users, source: :user, through: :likes
  
  
  def like(user)
    likes.create(user_id: user.id) #tweet_idが自動補完される
  end
  
  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end
  
  def liked?(user)
    like_users.include?(user)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :uid, presence: true, uniqueness: true
  validates :pass, presence: true
  
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_tweets, source: :tweet, through: :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
    def current_user
        if session[:login_uid]
          User.find_by(uid: session[:login_uid])
        end
    end
    helper_method :current_user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    tweet = Tweet.find(params[:tweet_id])
    unless tweet.liked?(current_user)
      tweet.like(current_user)
    end
    redirect_to tweets_path
  end
  
  def destroy
    tweet = Tweet.find(params[:id])
    if tweet.liked?(current_user)
      tweet.unlike(current_user)
    end
    redirect_to tweets_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def main
     if session[:login_uid] == nil
       render 'login'
     else
       render 'main'
     end
  end
  
  def login
     user = User.find_by(uid: params[:uid])
    if user && user.pass == params[:pass]
      session[:login_uid] = params[:uid]
	    redirect_to tweets_path
    else
      render 'error'
    end
  end
  
  def logout
    session[:login_uid] = nil
    redirect_to tops_main_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end
  
  def new
    @tweet = Tweet.new
  end
  
  def create
  @tweet = Tweet.new(message: params[:tweet][:message], tdate: params[:tweet][:tdate])
  @tweet.user_id = current_user.id
    if @tweet.save
      redirect_to tweets_path
    else
      render 'new'
    end
  end
  
  def destroy
  @tweet = Tweet.find(params[:id])
  @tweet.destroy
  redirect_to tweets_path
  end
  
  def show
  @tweet = Tweet.find(params[:id])
  end
  
  def edit
  @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    @tweet.update(message: params[:tweet][:message], tdate: params[:tweet][:tdate])
    redirect_to tweets_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
     @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(uid: params[:user][:uid], pass: params[:user][:pass])
      if @user.save
        redirect_to root_path
      else
        render 'new'
      end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tops/error.html.erb
<h3 style = "color: red;">ログインERROR!</h3>

<%= link_to 'BACK', '/' %>

app/views/tops/login.html.erb
<%= form_tag '/tops/login', method: :post do %>
  <%= label_tag :uid, 'ユーザーID' %>
  <%= text_field_tag :uid %>
  <%= label_tag :pass, 'パスワード' %>
  <%= password_field_tag :pass %>
  <%= submit_tag 'ログイン' %>
<% end %>

<p><%= link_to '新規登録', new_user_path %></p>  

app/views/tops/main.html.erb
<p><%= link_to 'ツイート一覧', tweets_path %></p>
<p><%=link_to 'ユーザ一覧', users_path %></p>
<p><%= link_to 'ログアウト', tops_logout_path %></p>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
  <%= f.text_area :message, size: "50x4" %>
  <% @tweet.tdate = Time.current %>
  <%= f.hidden_field :tdate %><br/>
  <%= f.submit 'ツイート' %>
<% end %>
  

app/views/tweets/index.html.erb
<html>
  <head>
    <title>Twitter</title>
  </head>
  <body id="page">
   <h2>ツイート一覧</h2> 

 
<% @tweets.each do |t|%>
  < <%= User.find(t.user_id).uid %> >
<br/>
  <%= t.message %>&ensp;
  <%= (Time.current - t.tdate).to_i / 60 %>分前&ensp;
  
  <% if t.liked?(current_user) %>
    <%= link_to 'いいね削除', like_path(t), method: :delete %>
  <% else %>
    <%= link_to 'いいね', likes_path(tweet_id: t.id), method: :post %>
  <% end %>
  &ensp;
  <% if current_user.id == t.user_id %>
    <%= link_to '削除', tweet_path(t), method: :delete, data: { confirm: '削除ok?' } %>
  <% end %>
  &ensp;
  <%= link_to '表示', tweet_path(t) %>
  &ensp;
  <%= link_to '編集', edit_tweet_path(t) %>
  <br/><br/><hr><br/>
<% end %>
<p><%=link_to 'ツイート', new_tweet_path %></p>
<p><%=link_to 'ユーザ一覧', users_path %></p>
<p><%= link_to 'ログアウト', tops_logout_path %></p>
 </body>
</html>

app/views/tweets/new.html.erb
<% if @tweet.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
  <% @tweet.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>
<br/>
<%= form_for @tweet do |f| %>
 <%= f.text_area :message, size: "50x4" %>
 <% @tweet.tdate = Time.current %>
 <%= f.hidden_field :tdate %><br/>
 <%= f.submit 'ツイート' %>
<% end %>

app/views/tweets/show.html.erb
<p>
  <%= @tweet.message %>
&ensp;
  <%= (Time.current - @tweet.tdate).to_i / 60 %>分前
</p>

<%= link_to 'Back',tweets_path %>

app/views/users/index.html.erb
<h2>ユーザ一覧</h2>

<% @users.each do |u| %>
 <%= u.uid %>&ensp;
 <%= link_to '削除', user_path(u), method: :delete %>
<% end %> 
<br/><hr><br/>
<%= link_to 'Back',tweets_path %>

app/views/users/new.html.erb
<%= form_for @user, url: {action: "create"} do |f| %>
  <%= f.label :uid, 'ユーザID' %>
  <%= f.text_field :uid %>
  <%= f.label :pass, 'パスワード' %>
  <%= f.password_field :pass %>
  <%= f.submit '登録' %>
<% end %>